# Generated by Django 6.1.1 on 2026-09-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('debit', 'Учебная оплата картой (без списания)'), ('wallet', 'Учебная оплата кошельком (без списания)'), ('cod', 'Оплата при получении')], max_length=20),
        ),
    ]
