# Generated by Django 6.1.1 on 2026-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('debit', 'Оплата картой'), ('wallet', 'Оплата криптой'), ('cod', 'Оплата при получении')], max_length=20),
        ),
    ]
